const CREDIT_CARD_DATA_LOADED = "CREDIT_CARD_DATA_LOADED"
const CREDIT_CARD_API_ERRORED = "CREDIT_CARD_API_ERRORED"
const CREDIT_CARD_DATA_REQUESTED = "CREDIT_CARD_DATA_REQUESTED"
const CREDIT_CARD_ADD_REQUESTED = "CREDIT_CARD_ADD_REQUESTED"
const CREDIT_CARD_ADD_API_ERRORED = "CREDIT_CARD_ADD_API_ERRORED"
const CREDIT_CARD_ADD_API_SUCCESS = "CREDIT_CARD_ADD_API_SUCCESS"
const CREDIT_CARD_STAGE_INPUT_DATA_REQUESTED = 'CREDIT_CARD_STAGE_INPUT_DATA_REQUESTED'

export {
  CREDIT_CARD_DATA_LOADED,
  CREDIT_CARD_API_ERRORED,
  CREDIT_CARD_DATA_REQUESTED,
  CREDIT_CARD_ADD_REQUESTED,
  CREDIT_CARD_ADD_API_ERRORED,
  CREDIT_CARD_ADD_API_SUCCESS,
  CREDIT_CARD_STAGE_INPUT_DATA_REQUESTED
}

