const CREDIT_CARD_DATA_LOADED = "CREDIT_CARD_DATA_LOADED"
const CREDIT_CARD_API_ERRORED = "CREDIT_CARD_API_ERRORED"
const CREDIT_CARD_DATA_REQUESTED = "CREDIT_CARD_DATA_REQUESTED"

export {
  CREDIT_CARD_DATA_LOADED,
  CREDIT_CARD_API_ERRORED,
  CREDIT_CARD_DATA_REQUESTED
}

